# ptang@leqee.com

version: '2.2'

services:
  cat:
    image: rolesle/cat:0.0.1
    container_name: cat
    environment:
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=rm-k2ja1n6byl5rg974i.mysql.zhangbei.rds.aliyuncs.com # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=infra_cat
      - MYSQL_PASSWD=dlS87dD43f
      - MYSQL_SCHEMA=cat
      - SERVER_IP=10.0.16.134
    working_dir: /app
    volumes:
      - "./cat_client.xml:/data/appdatas/cat/client.xml"
      - "./cat_datasources.xml:/data/appdatas/cat/datasources.xml"
    command: /bin/sh -c 'cat $CATALINA_HOME/conf/server.xml && catalina.sh run'
    ports:
      - "30000:8080"
      - "2280:2280"
    network_mode: "host"
   
  zookeeper:
    image: zookeeper:3.4.14
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000